spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt?serverTimezone=UTC
    username: root
    password:
    initialization-mode: always
    data: classpath:/data/data_user.sql

  jpa:
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#  jpa:
#    show-sql: true
#    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create
#      naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy


